name: arsen_take_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

workspace:
  - modules/core
  - modules/weather
  - packages/design_system
dependencies:
  auto_route: ^10.2.0
  design_system: ^0.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  injectable: ^2.5.2
  weather: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  auto_route_generator: ^10.2.5
  injectable_generator: ^2.9.0

flutter:
  assets:
      - .env
  uses-material-design: true


