name: core
environment:
  sdk: ^3.8.0
resolution: workspace
dependencies:
  auto_route: ^10.2.0
  dio: ^5.9.0
  injectable: ^2.5.2
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.9.0